---
title: "3 - Visualization"
author: "Alejandro Aísa, Álvaro Sanz"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(data.table)
library(lubridate)
library(showtext)
```


# Importing the data

```{r}
#dfull <- read.csv("data/predicted.csv")
dfull <- fread("data/predicted.csv")
```

# Data transforming

```{r}
min(dfull$created_at)
max(dfull$created_at)
```

```{r}
dfull2 <- dfull
dfull <- dfull %>% 
  mutate(created_at = ymd_hms(created_at),
         created_at = format(created_at, "%Y-%m-%d %H:00:00"))

viz <- dfull %>% 
  mutate(hate = factor(hate, levels = c("No", "Yes"))) %>% 
  group_by(created_at) %>% 
  summarise(No_count = sum(hate == "No", na.rm = TRUE),
            Yes_count = sum(hate == "Yes", na.rm = TRUE),
            Total = sum(No_count, Yes_count),
            Proportion = Yes_count/Total * 100)

```

```{r}
viz <- viz %>% 
  mutate(match = case_when(created_at == "2022-11-23 15:00:00" | created_at == "2022-11-23 16:00:00" | created_at == "2022-11-23 17:00:00" | created_at == "2022-11-23 18:00:00" | created_at == "2022-11-23 19:00:00" | created_at == "2022-11-23 20:00:00" | created_at == "2022-11-23 21:00:00" | created_at == "2022-11-23 17:00:00" | created_at == "2022-11-27 18:00:00" | created_at == "2022-11-27 19:00:00" | created_at == "2022-11-27 20:00:00" | created_at == "2022-11-27 21:00:00" | created_at == "2022-11-27 22:00:00" | created_at == "2022-11-27 23:00:00" | created_at == "2022-11-27 24:00:00" | created_at == "2022-12-01 18:00:00" | created_at == "2022-12-01 19:00:00" | created_at == "2022-12-01 20:00:00" | created_at == "2022-12-01 21:00:00" | created_at == "2022-12-01 22:00:00" | created_at == "2022-12-01 23:00:00" | created_at == "2022-12-01 24:00:00" | created_at == "2022-12-06 14:00:00" | created_at == "2022-12-06 15:00:00" | created_at == "2022-12-06 16:00:00" | created_at == "2022-12-06 17:00:00" | created_at == "2022-12-06 18:00:00" | created_at == "2022-12-06 19:00:00" ~ 1,
                           T ~ 0),
         match = factor(match, levels = c(0,1)), 
         costarica = factor(ifelse((match == 1 & day(created_at) == 23), 1, 0), levels = c(0,1)),
         germany = factor(ifelse((match == 1 & day(created_at) == 27), 1, 0), levels = c(0,1)),
         japan = factor(ifelse((match == 1 & day(created_at) == 01), 1, 0), levels = c(0,1)),
         morocco = factor(ifelse((match == 1 & day(created_at) == 06), 1, 0), levels = c(0,1)))
```

# Visualization

```{r}
sysfonts::font_add_google("Titillium Web", family="titillium")
showtext::showtext_auto()
```

```{r}
library(png)
germanyflag <- readPNG("data/images/1200px-Flag_of_Germany.png")
japanflag <- readPNG("data/images/Flag_of_Japan.png")
crflag <- readPNG("data/images/Flag_of_Costa_Rica.png")
morflag <- readPNG("data/images/Flag_of_Morocco.png")
```


```{r,fig.height=5, fig.width=8,  out.height="100%", out.width="100%"}
library(grid)

vizjap <- viz %>% 
  filter(match == 1 & japan == 1)
vizcr <- viz %>% 
  filter(match == 1 & costarica == 1)
vizger <- viz %>% 
  filter(match == 1 & germany == 1)
vizmor <- viz %>% 
  filter(match == 1 & morocco == 1)



viz %>% 
  ggplot() +
  aes(x = as.POSIXct(created_at), y = Proportion) +
  geom_rect(aes(xmin=as.POSIXct("2022-11-23 15:00"), xmax=as.POSIXct("2022-11-23 21:00"), ymin=(-Inf), ymax=Inf),
            alpha=0.1, show.legend=FALSE, fill = "lightgrey") + #Costa Rica
  geom_rect(aes(xmin=as.POSIXct("2022-11-27 18:00"), xmax=as.POSIXct("2022-11-28 00:00"), ymin=(-Inf), ymax=Inf),
            alpha=0.1, show.legend=FALSE, fill = "lightgrey") + #Germany
  geom_rect(aes(xmin=as.POSIXct("2022-12-01 18:00"), xmax=as.POSIXct("2022-12-02 00:00"), ymin=(-Inf), ymax=Inf),
            alpha=0.1, show.legend=FALSE, fill = "lightgrey") + #Japan
  geom_rect(aes(xmin=as.POSIXct("2022-12-06 14:00"), xmax=as.POSIXct("2022-12-06 19:00"), ymin=(-Inf), ymax=Inf),
            alpha=0.1, show.legend=FALSE, fill = "lightgrey") + #Morocco
  geom_line() +
  geom_line(data = vizjap, aes(x = as.POSIXct(created_at), y = Proportion), color = "orange") +
  geom_line(data = vizcr, aes(x = as.POSIXct(created_at), y = Proportion), color = "darkgreen") +
  geom_line(data = vizger, aes(x = as.POSIXct(created_at), y = Proportion), color = "orange") +
  geom_line(data = vizmor, aes(x = as.POSIXct(created_at), y = Proportion), color = "red") +
  scale_color_manual(aes(match), values = c("black", "orange")) +
  scale_y_continuous(
    limits = c(0,6),
    labels = function(x) paste0(x, "%")) +
  scale_x_datetime(date_labels = "%d/%m %Hh", date_breaks = "12 hours") +
  theme(axis.ticks.x.bottom = element_blank(),
        axis.text.x.bottom = element_text(angle = 45, vjust = 0.5, hjust = 1),
        text = element_text(family = "titillium", colour = "black"),
        axis.line.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(colour = "lightgrey", linetype = "dotted"),
        axis.ticks = element_line(color = "lightgrey"),
        panel.background = element_blank(),
        plot.margin = margin(t=0,
                         r=10,
                         b=0,
                         l=0),
        plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 14, face = "italic"),
        axis.title = element_text(size = 13),
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10))) +
  ylab("Proportion of hateful tweets") +
  xlab("Time when the tweet was sent") +
  labs(title = "The patterns of Spanish online hate speech",
       subtitle = "The % of hateful tweets increases the days after games, specially when Spain doesn't win \nand plays against teams from other continents") +
  annotate(
    "text", x = as.POSIXct("2022-12-09 06:00"), y = 5.5,
    label = "= Match",
    color = "black"
  ) +
  annotate(geom = "point", 
           x = as.POSIXct("2022-12-08 03:00"), y = 5.5, color = "grey", size = 3, shape = 16, alpha = 0.8) +
  annotate(
    "text", x = as.POSIXct("2022-12-09 06:00"), y = 5.1,
    label = "= Win",
    color = "black"
  ) +
  annotate(geom = "point", 
           x = as.POSIXct("2022-12-08 03:00"), y = 5.1, color = "darkgreen", size = 3, shape = 16) +
annotate(
    "text", x = as.POSIXct("2022-12-09 06:00"), y = 4.8,
    label = "  = Draw",
    color = "black"
  ) +
  annotate(geom = "point", 
           x = as.POSIXct("2022-12-08 03:00"), y = 4.8, color = "orange", size = 3, shape = 16) +
annotate(
    "text", x = as.POSIXct("2022-12-09 06:00"), y = 4.5,
    label = " = Loss",
    color = "black"
  ) +
  annotate(geom = "point", 
           x = as.POSIXct("2022-12-08 03:00"), y = 4.5, color = "red", size = 3, shape = 16) +
  annotate(geom = "segment", x = as.POSIXct("2022-12-08 03:00"), xend = as.POSIXct("2022-12-10 00:00"), y = 5.3, yend = 5.3, color = "black") +
  
  annotation_custom(rasterGrob(germanyflag, width = unit(1, "npc"), height = unit(1, "npc")),
                           xmin = as.POSIXct("2022-11-26 06:00:00"), xmax = as.POSIXct("2022-11-27 06:00:00"),
                           ymin = 5.5, ymax = 5.9) + #Germany
  annotation_custom(rasterGrob(crflag, width = unit(1, "npc"), height = unit(1, "npc")),
                           xmin = as.POSIXct("2022-11-22 03:00:00"), xmax = as.POSIXct("2022-11-23 03:00:00"),
                           ymin = 5.5, ymax = 5.9) + #Costa Rica
  annotation_custom(rasterGrob(japanflag, width = unit(1, "npc"), height = unit(1, "npc")),
                           xmin = as.POSIXct("2022-11-30 03:00:00"), xmax = as.POSIXct("2022-12-01 03:00:00"),
                           ymin = 5.5, ymax = 5.9) + #Japan
  annotation_custom(rasterGrob(morflag, width = unit(1, "npc"), height = unit(1, "npc")),
                           xmin = as.POSIXct("2022-12-04 22:00:00"), xmax = as.POSIXct("2022-12-05 22:00:00"),
                           ymin = 5.5, ymax = 5.9) + #Morocco
  annotate(geom = "segment",
         x = as.POSIXct("2022-11-26 06:00:00"),
         xend = as.POSIXct("2022-11-27 06:00:00"),
         y = 5.9, yend = 5.9,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-11-27 06:00:00"),
         xend = as.POSIXct("2022-11-27 06:00:00"),
         y = 5.9, yend = 5.5,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-11-26 06:00:00"),
         xend = as.POSIXct("2022-11-26 06:00:00"),
         y = 5.5, yend = 5.9,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-11-26 06:00:00"),
         xend = as.POSIXct("2022-11-27 06:00:00"),
         y = 5.5, yend = 5.5,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-11-22 03:00:00"),
         xend = as.POSIXct("2022-11-23 03:00:00"),
         y = 5.9, yend = 5.9,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-11-23 03:00:00"),
         xend = as.POSIXct("2022-11-23 03:00:00"),
         y = 5.9, yend = 5.5,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-11-22 03:00:00"),
         xend = as.POSIXct("2022-11-22 03:00:00"),
         y = 5.5, yend = 5.9,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-11-22 03:00:00"),
         xend = as.POSIXct("2022-11-23 03:00:00"),
         y = 5.5, yend = 5.5,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-11-30 03:00:00"),
         xend = as.POSIXct("2022-12-01 03:00:00"),
         y = 5.9, yend = 5.9,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-12-01 03:00:00"),
         xend = as.POSIXct("2022-12-01 03:00:00"),
         y = 5.9, yend = 5.5,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-11-30 03:00:00"),
         xend = as.POSIXct("2022-11-30 03:00:00"),
         y = 5.5, yend = 5.9,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-11-30 03:00:00"),
         xend = as.POSIXct("2022-12-01 03:00:00"),
         y = 5.5, yend = 5.5,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-12-04 22:00:00"),
         xend = as.POSIXct("2022-12-05 22:00:00"),
         y = 5.9, yend = 5.9,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-12-05 22:00:00"),
         xend = as.POSIXct("2022-12-05 22:00:00"),
         y = 5.9, yend = 5.5,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-12-04 22:00:00"),
         xend = as.POSIXct("2022-12-04 22:00:00"),
         y = 5.5, yend = 5.9,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-12-04 22:00:00"),
         xend = as.POSIXct("2022-12-05 22:00:00"),
         y = 5.5, yend = 5.5,
         color = "black") +
# Annotation for Germany (diagonal segment)
  annotate(geom = "segment",
         x = as.POSIXct("2022-11-27 06:00:00"),
         xend = as.POSIXct("2022-11-27 18:00:00"),
         y = 5.5, yend = 5.3,
         color = "black") +

# Annotation for Costa Rica (diagonal segment)
annotate(geom = "segment",
         x = as.POSIXct("2022-11-23 03:00:00"),
         xend = as.POSIXct("2022-11-23 15:00:00"),
         y = 5.5, yend = 5.3,
         color = "black") +

# Annotation for Japan (diagonal segment)
annotate(geom = "segment",
         x = as.POSIXct("2022-12-01 03:00:00"),
         xend = as.POSIXct("2022-12-01 18:00:00"),
         y = 5.5, yend = 5.3,
         color = "black") +

# Annotation for Morocco (diagonal segment)
annotate(geom = "segment",
         x = as.POSIXct("2022-12-05 22:00:00"),
         xend = as.POSIXct("2022-12-06 14:00:00"),
         y = 5.5, yend = 5.3,
         color = "black")

  
#ggsave("test.jpeg", width = 14, height = 10, dpi = 300)

```


# Inside Spain vs. Morocco

```{r}
dfull2 <- dfull2 %>% 
  filter(created_at>="2022-12-06 14:00:00" & created_at<"2022-12-07 00:00:00") %>% 
  mutate(created_at = ymd_hms(created_at),
         created_at = format(created_at, "%Y-%m-%d %H:%M:00"),
         created_at = ymd_hms(created_at)) %>% 
  mutate(hate = factor(hate, levels = c("No", "Yes")),
         created_at = round_date(created_at, unit = "10 minutes")) %>% 
  group_by(created_at) %>% 
  summarise(No_count = sum(hate == "No", na.rm = TRUE),
            Yes_count = sum(hate == "Yes", na.rm = TRUE),
            Total = sum(No_count, Yes_count),
            Proportion = Yes_count/Total * 100)
```

```{r}
dfull2 %>% 
  ggplot() +
  aes(x = as.POSIXct(created_at), y = Proportion) +
  geom_rect(aes(xmin=as.POSIXct("2022-12-06 16:00"), xmax=as.POSIXct("2022-12-06 19:00"), ymin=(-Inf), ymax=Inf),
            alpha=0.1, show.legend=FALSE, fill = "lightgrey") +
  geom_line() +
  scale_y_continuous(
    limits = c(0,6),
    labels = function(x) paste0(x, "%")) +
  scale_x_datetime(date_labels = "%H:%M", date_breaks = "30 mins") +
  theme(axis.text.x.bottom = element_text(angle = 45, vjust = 1, hjust = 1, size = 9),
        axis.ticks.x.bottom = element_blank(),
        text = element_text(family = "titillium", colour = "black"),
        axis.line.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(colour = "lightgrey", linetype = "dotted"),
        axis.ticks = element_line(color = "lightgrey"),
        panel.background = element_blank(),
        plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 14, face = "italic"),
        axis.title = element_text(size = 13),
        axis.title.x.bottom = element_text(vjust = 0)) +
  ylab("Proportion of hateful tweets") +
  xlab("Time when the tweet was sent") +
  labs(title = "Hate speech concentrates Before & After the match",
       subtitle = "Blabla") +
  annotate(
    "text", x = as.POSIXct("2022-12-06 23:00"), y = 5.5,
    label = "= Match",
    color = "black"
  ) +
  annotate(geom = "point", 
           x = as.POSIXct("2022-12-06 22:25"), y = 5.5, color = "grey", size = 3, shape = 16, alpha = 0.8) +
  annotation_custom(rasterGrob(morflag, width = unit(1, "npc"), height = unit(1, "npc")),
                           xmin = as.POSIXct("2022-12-06 17:00:00"), xmax = as.POSIXct("2022-12-06 18:00:00"),
                           ymin = 5, ymax = 5.8) +
  annotate(geom = "segment",
         x = as.POSIXct("2022-12-06 17:00:00"),
         xend = as.POSIXct("2022-12-06 18:00:00"),
         y = 5, yend = 5,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-12-06 18:00:00"),
         xend = as.POSIXct("2022-12-06 18:00:00"),
         y = 5, yend = 5.8,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-12-06 18:00:00"),
         xend = as.POSIXct("2022-12-06 17:00:00"),
         y = 5.8, yend = 5.8,
         color = "black") +
annotate(geom = "segment",
         x = as.POSIXct("2022-12-06 17:00:00"),
         xend = as.POSIXct("2022-12-06 17:00:00"),
         y = 5.8, yend = 5,
         color = "black")
```


# T-tests

All: 

```{r}

s<-split(viz$Proportion,viz$match) #splits the variable price in two groups by gender

#first step: test for equal variances
var.test(s$`0`, s$`1`, alternative = "two.sided")
#second step: test for differences of means, knowing that variances are different
t.test(s$`0`, s$`1` ,alternative="two.sided",mu=0,var.equal=FALSE)  ##The only thing that changes is the last part, var.equal has to be =FALSE. 
##It also gives the difference's confidence interval --> In this case it's + (both values), so males's proportion is greater. 
```

Morocco: 

```{r}

s<-split(viz$Proportion,viz$morocco) #splits the variable price in two groups by gender

#first step: test for equal variances
var.test(s$`0`, s$`1`, alternative = "two.sided")
#second step: test for differences of means, knowing that variances are different
t.test(s$`1`, s$`0`, alternative="greater",mu=0.8,var.equal=TRUE)  ##The only thing that changes is the last part, var.equal has to be =FALSE. 
##It also gives the difference's confidence interval --> In this case it's + (both values), so males's proportion is greater. 
```

Costa Rica: 

```{r}
s<-split(viz$Proportion,viz$morocco) #splits the variable price in two groups by gender

#first step: test for equal variances
var.test(s$`0`, s$`1`, alternative = "two.sided")
#second step: test for differences of means, knowing that variances are different
t.test(s$`1`, s$`0`, alternative="greater",mu=0.8,var.equal=TRUE)  ##The only thing that changes is the last part, var.equal has to be =FALSE. 
##It also gives the difference's confidence interval --> In this case it's + (both values), so males's proportion is greater. 
```

Japan: 

```{r}
s<-split(viz$Proportion,viz$morocco) #splits the variable price in two groups by gender

#first step: test for equal variances
var.test(s$`0`, s$`1`, alternative = "two.sided")
#second step: test for differences of means, knowing that variances are different
t.test(s$`1`, s$`0`, alternative="greater",mu=0.8,var.equal=TRUE)  ##The only thing that changes is the last part, var.equal has to be =FALSE. 
##It also gives the difference's confidence interval --> In this case it's + (both values), so males's proportion is greater. 
```

Germany: 

```{r}
s<-split(viz$Proportion,viz$morocco) #splits the variable price in two groups by gender

#first step: test for equal variances
var.test(s$`0`, s$`1`, alternative = "two.sided")
#second step: test for differences of means, knowing that variances are different
t.test(s$`1`, s$`0`, alternative="greater",mu=0.8,var.equal=TRUE)  ##The only thing that changes is the last part, var.equal has to be =FALSE. 
##It also gives the difference's confidence interval --> In this case it's + (both values), so males's proportion is greater. 
```

